boxSize        = 40
xInitial       = -0.973
xOffset        = 0.067
customizations = {
  [1] = { checkboxes = { posZ = -0.939, count = 1 } },
  [2] = { checkboxes = { posZ = -0.741, count = 1 } },
  [3] = { checkboxes = { posZ = -0.366, count = 1 } },
  [4] = { checkboxes = { posZ = 0.096, count = 1 } },
  [5] = { checkboxes = { posZ = 0.280, count = 1 } },
  [6] = { checkboxes = { posZ = 0.384, count = 1 } },
  [7] = { checkboxes = { posZ = 0.758, count = 3 } },
  [8] = { checkboxes = { posZ = 0.957, count = 3 } },
  [9] = { checkboxes = { posZ = 1.156, count = 4 } }
}
require("playercards/customizable/UpgradeSheetLibrary")
