boxSize        = 40
xInitial       = -0.984
xOffset        = 0.077
customizations = {
  [1] = { checkboxes = { posZ = -0.922, count = 1 } },
  [2] = { checkboxes = { posZ = -0.685, count = 2 } },
  [3] = { checkboxes = { posZ = -0.351, count = 2 } },
  [4] = { checkboxes = { posZ = -0.117, count = 2 } },
  [5] = { checkboxes = { posZ = 0.117, count = 2 } },
  [6] = { checkboxes = { posZ = 0.454, count = 3 } },
  [7] = { checkboxes = { posZ = 0.894, count = 3 } }
}
require("playercards/customizable/UpgradeSheetLibrary")
