boxSize        = 40
xInitial       = -0.982
xOffset        = 0.071
customizations = {
  [1] = { checkboxes = { posZ = -0.925, count = 1 } },
  [2] = { checkboxes = { posZ = -0.426, count = 2 } },
  [3] = { checkboxes = { posZ = -0.210, count = 2 } },
  [4] = { checkboxes = { posZ = 0.195, count = 3 } },
  [5] = { checkboxes = { posZ = 0.505, count = 3 } },
  [6] = { checkboxes = { posZ = 1.006, count = 4 } }
}
require("playercards/customizable/UpgradeSheetLibrary")
