boxSize        = 35
inputFontsize  = 35
xInitial       = -0.982
xOffset        = 0.062
customizations = {
  [1] = { textField = { position = { -0, 0.25, -0.805 }, width = 600 } },
  [2] = { checkboxes = { posZ = -0.682, count = 1 } },
  [3] = { checkboxes = { posZ = -0.478, count = 1 } },
  [4] = { checkboxes = { posZ = -0.275, count = 2 } },
  [5] = {
    checkboxes = { posZ = -0.071, count = 2 },
    textField = { position = { -0.05, 0.25, 0.13 }, width = 860 }
  },
  [6] = { checkboxes = { posZ = 0.223, count = 2 } },
  [7] = { checkboxes = { posZ = 0.518, count = 3 } },
  [8] = { checkboxes = { posZ = 0.811, count = 4 } }
}
require("playercards/customizable/UpgradeSheetLibrary")
