boxSize        = 40
xInitial       = -0.980
xOffset        = 0.069
customizations = {
  [1] = { checkboxes = { posZ = -0.948, count = 1 } },
  [2] = { checkboxes = { posZ = -0.736, count = 1 } },
  [3] = { checkboxes = { posZ = -0.526, count = 1 } },
  [4] = { checkboxes = { posZ = -0.315, count = 1 } },
  [5] = { checkboxes = { posZ = -0.104, count = 2 } },
  [6] = { checkboxes = { posZ = 0.389, count = 2 } },
  [7] = { checkboxes = { posZ = 0.696, count = 3 } },
  [8] = { checkboxes = { posZ = 1.000, count = 4 } }
}
require("playercards/customizable/UpgradeSheetLibrary")
