boxSize        = 40
xInitial       = -0.986
xOffset        = 0.080
customizations = {
  [1] = { checkboxes = { posZ = -0.914, count = 1 } },
  [2] = { checkboxes = { posZ = -0.675, count = 1 } },
  [3] = { checkboxes = { posZ = -0.435, count = 1 } },
  [4] = { checkboxes = { posZ = -0.085, count = 1 } },
  [5] = { checkboxes = { posZ = 0.155, count = 2 } },
  [6] = { checkboxes = { posZ = 0.505, count = 4 } },
  [7] = { checkboxes = { posZ = 1.065, count = 5 } }
}
require("playercards/customizable/UpgradeSheetLibrary")
