-- Customizable Cards: 09042-c

boxSize  = 40
xInitial = -0.982
xOffset  = 0.062

customizations = {
  [1] = {
    checkboxes = {
      posZ = -0.682,
      count = 1
    }
  },
  [2] = {
    checkboxes = {
      posZ = -0.478,
      count = 1
    }
  },
  [3] = {
    checkboxes = {
      posZ = -0.275,
      count = 2
    }
  },
  [4] = {
    checkboxes = {
      posZ = -0.071,
      count = 2
    }
  },
  [5] = {
    checkboxes = {
      posZ = 0.223,
      count = 2
    }
  },
  [6] = {
    checkboxes = {
      posZ = 0.518,
      count = 3
    }
  },
  [7] = {
    checkboxes = {
      posZ = 0.811,
      count = 4
    }
  },
}
require("playercards/customizable/UpgradeSheetLibrary")