-- Customizable Cards: 09059-c

boxSize  = 40
xInitial = -0.987
xOffset  = 0.076

customizations = {
  [1] = {
    checkboxes = {
      posZ = -0.949,
      count = 1
    }
  },
  [2] = {
    checkboxes = {
      posZ = -0.494,
      count = 2
    }
  },
  [3] = {
    checkboxes = {
      posZ = -0.147,
      count = 2
    }
  },
  [4] = {
    checkboxes = {
      posZ = 0.096,
      count = 3
    }
  },
  [5] = {
    checkboxes = {
      posZ = 0.550,
      count = 3
    }
  },
  [6] = {
    checkboxes = {
      posZ = 0.897,
      count = 4
    }
  },
}
require("playercards/customizable/UpgradeSheetLibrary")