boxSize        = 40
inputFontsize  = 50
xInitial       = -0.987
xOffset        = 0.072
customizations = {
  [1] = { textField = { position = { 0.275, 0.25, -0.91 }, width = 640 } },
  [2] = { checkboxes = { posZ = -0.752, count = 1 } },
  [3] = {
    checkboxes = { posZ = -0.440, count = 2 },
    textField  = { position = { 0.6295, 0.25, -0.44 }, width = 290 }
  },
  [4] = { checkboxes = { posZ = 0.067, count = 2 } },
  [5] = { checkboxes = { posZ = 0.382, count = 2 } },
  [6] = { checkboxes = { posZ = 0.694, count = 2 } },
  [7] = { checkboxes = { posZ = 1.009, count = 3 } },
  [8] = { checkboxes = { posZ = 1.225, count = 3 } }
}
require("playercards/customizable/UpgradeSheetLibrary")
