-- Customizable Cards: 09060-c

boxSize  = 40
xInitial = -0.987
xOffset  = 0.072

customizations = {
  [1] = {
    checkboxes = {
      posZ = -0.752,
      count = 1
    }
  },
  [2] = {
    checkboxes = {
      posZ = -0.440,
      count = 2
    }
  },
  [3] = {
    checkboxes = {
      posZ = 0.067,
      count = 2
    }
  },
  [4] = {
    checkboxes = {
      posZ = 0.382,
      count = 2
    }
  },
  [5] = {
    checkboxes = {
      posZ = 0.694,
      count = 2
    }
  },
  [6] = {
    checkboxes = {
      posZ = 1.009,
      count = 3
    }
  },
  [7] = {
    checkboxes = {
      posZ = 1.225,
      count = 3
    }
  },
}
require("playercards/customizable/UpgradeSheetLibrary")