boxSize        = 40
xInitial       = -0.979
xOffset        = 0.071
customizations = {
  [1] = { checkboxes = { posZ = -0.922, count = 1 } },
  [2] = { checkboxes = { posZ = -0.604, count = 1 } },
  [3] = { checkboxes = { posZ = -0.287, count = 1 } },
  [4] = { checkboxes = { posZ = -0.067, count = 1 } },
  [5] = { checkboxes = { posZ = 0.248, count = 1 } },
  [6] = { checkboxes = { posZ = 0.467, count = 2 } },
  [7] = { checkboxes = { posZ = 0.783, count = 3 } },
  [8] = { checkboxes = { posZ = 1.100, count = 5 } }
}
require("playercards/customizable/UpgradeSheetLibrary")
