boxSize              = 40
xInitial             = -0.984
xOffset              = 0.074
SKILL_ICON_POSITIONS = {
  willpower = { x = 0.085, z = -0.88 },
  intellect = { x = -0.183, z = -0.88 },
  combat    = { x = -0.473, z = -0.88 },
  agility   = { x = -0.74, z = -0.88 }
}
customizations       = {
  [1] = {},
  [2] = { checkboxes = { posZ = -0.722, count = 1 } },
  [3] = { checkboxes = { posZ = -0.487, count = 1 } },
  [4] = { checkboxes = { posZ = -0.145, count = 2 } },
  [5] = { checkboxes = { posZ = 0.193, count = 2 } },
  [6] = { checkboxes = { posZ = 0.429, count = 3 } },
  [7] = { checkboxes = { posZ = 0.664, count = 3 } },
  [8] = { checkboxes = { posZ = 1.108, count = 3 } }
}
require("playercards/customizable/UpgradeSheetLibrary")
