-- Customizable Cards: 09079-c

boxSize  = 40
xInitial = -0.984
xOffset  = 0.074

customizations = {
  [1] = {
    checkboxes = {
      posZ = -0.722,
      count = 1
    }
  },
  [2] = {
    checkboxes = {
      posZ = -0.487,
      count = 1
    }
  },
  [3] = {
    checkboxes = {
      posZ = -0.145,
      count = 2
    }
  },
  [4] = {
    checkboxes = {
      posZ = 0.193,
      count = 2
    }
  },
  [5] = {
    checkboxes = {
      posZ = 0.429,
      count = 3
    }
  },
  [6] = {
    checkboxes = {
      posZ = 0.664,
      count = 3
    }
  },
  [7] = {
    checkboxes = {
      posZ = 1.108,
      count = 3
    }
  },
}
require("playercards/customizable/UpgradeSheetLibrary")