boxSize             = 40
xInitial            = -0.984
xOffset             = 0.067
SLOT_ICON_POSITIONS = {
  arcane = { x = 0.160, z = 0.65, width = 0.12 },
  ally   = { x = -0.073, z = 0.65, width = 0.07 }
}
SLOT_INDICES        = { arcane = "1", ally = "0", none = "" }
customizations      = {
  [1] = { checkboxes = { posZ = -0.958, count = 1 } },
  [2] = { checkboxes = { posZ = -0.661, count = 1 } },
  [3] = { checkboxes = { posZ = -0.270, count = 1 } },
  [4] = { checkboxes = { posZ = 0.120, count = 1 } },
  [5] = { checkboxes = { posZ = 0.328, count = 1 } },
  [6] = { checkboxes = { posZ = 0.626, count = 2 } },
  [7] = { checkboxes = { posZ = 0.833, count = 3 } },
  [8] = { checkboxes = { posZ = 1.132, count = 5 } }
}
require("playercards/customizable/UpgradeSheetLibrary")
