boxSize        = 40
xInitial       = -0.985
xOffset        = 0.062
customizations = {
  [1] = { checkboxes = { posZ = -0.945, count = 1 } },
  [2] = { checkboxes = { posZ = -0.662, count = 1 } },
  [3] = { checkboxes = { posZ = -0.292, count = 1 } },
  [4] = { checkboxes = { posZ = -0.009, count = 1 } },
  [5] = { checkboxes = { posZ = 0.362, count = 2 } },
  [6] = { checkboxes = { posZ = 0.559, count = 3 } },
  [7] = { checkboxes = { posZ = 0.840, count = 3 } },
  [8] = { checkboxes = { posZ = 1.038, count = 3 } }
}
require("playercards/customizable/UpgradeSheetLibrary")
