-- Customizable Cards: 09080-c

boxSize  = 40
xInitial = -0.984
xOffset  = 0.067

customizations = {
  [1] = {
    checkboxes = {
      posZ = -0.958,
      count = 1
    }
  },
  [2] = {
    checkboxes = {
      posZ = -0.661,
      count = 1
    }
  },
  [3] = {
    checkboxes = {
      posZ = -0.270,
      count = 1
    }
  },
  [4] = {
    checkboxes = {
      posZ = 0.120,
      count = 1
    }
  },
  [5] = {
    checkboxes = {
      posZ = 0.328,
      count = 1
    }
  },
  [6] = {
    checkboxes = {
      posZ = 0.626,
      count = 2
    }
  },
  [7] = {
    checkboxes = {
      posZ = 0.833,
      count = 3
    }
  },
  [8] = {
    checkboxes = {
      posZ = 1.132,
      count = 5
    }
  },
}
require("playercards/customizable/UpgradeSheetLibrary")