boxSize        = 40
xInitial       = -0.986
xOffset        = 0.071
customizations = {
  [1] = { checkboxes = { posZ = -0.925, count = 1 } },
  [2] = { checkboxes = { posZ = -0.595, count = 1 } },
  [3] = { checkboxes = { posZ = -0.265, count = 2 } },
  [4] = { checkboxes = { posZ = -0.035, count = 2 } },
  [5] = { checkboxes = { posZ = 0.293, count = 2 } },
  [6] = { checkboxes = { posZ = 0.522, count = 3 } },
  [7] = { checkboxes = { posZ = 0.852, count = 4 } }
}
require("playercards/customizable/UpgradeSheetLibrary")
