boxSize        = 40
inputFontsize  = 50
xInitial       = -0.982
xOffset        = 0.072
customizations = {
  [1] = { textField = { position = { 0.3, 0.25, -0.91 }, width = 600 } },
  [2] = {
    checkboxes = { posZ = -0.732, count = 1 },
    textField  = { position = { 0.005, 0.25, -0.58 }, width = 875 }
  },
  [3] = {
    checkboxes = { posZ = -0.487, count = 2 },
    textField  = { position = { 0.005, 0.25, -0.32 }, width = 875 }
  },
  [4] = { checkboxes = { posZ = -0.239, count = 3 } },
  [5] = { checkboxes = { posZ = 0.309, count = 4 } },
  [6] = { checkboxes = { posZ = 0.856, count = 5 } },
}
require("playercards/customizable/UpgradeSheetLibrary")
