-- Customizable Cards: 09101-c

boxSize  = 40
xInitial = -0.982
xOffset  = 0.072

customizations = {
  [1] = {
    checkboxes = {
      posZ = -0.732,
      count = 1
    }
  },
  [2] = {
    checkboxes = {
      posZ = -0.487,
      count = 2
    }
  },
  [3] = {
    checkboxes = {
      posZ = -0.239,
      count = 3
    }
  },
  [4] = {
    checkboxes = {
      posZ = 0.309,
      count = 4
    }
  },
  [5] = {
    checkboxes = {
      posZ = 0.856,
      count = 5
    }
  },
}
require("playercards/customizable/UpgradeSheetLibrary")