-- Customizable Cards: 09100-c

boxSize  = 40
xInitial = -0.985
xOffset  = 0.069

customizations = {
  [1] = {
    checkboxes = {
      posZ = -0.927,
      count = 1
    }
  },
  [2] = {
    checkboxes = {
      posZ = -0.618,
      count = 1
    }
  },
  [3] = {
    checkboxes = {
      posZ = -0.212,
      count = 2
    }
  },
  [4] = {
    checkboxes = {
      posZ = 0.099,
      count = 2
    }
  },
  [5] = {
    checkboxes = {
      posZ = 0.411,
      count = 2
    }
  },
  [6] = {
    checkboxes = {
      posZ = 0.720,
      count = 3
    }
  },
  [7] = {
    checkboxes = {
      posZ = 1.032,
      count = 4
    }
  },
}
require("playercards/customizable/UpgradeSheetLibrary")