boxSize        = 35
inputFontsize  = 35
xInitial       = -0.982
xOffset        = 0.072
customizations = {
  [1] = { textField = { position = { 0.29, 0.25, -0.92 }, width = 480 } },
  [2] = {
    checkboxes = { posZ = -0.732, count = 1 },
    textField  = { position = { -0.02, 0.25, -0.60 }, width = 890 }
  },
  [3] = {
    checkboxes = { posZ = -0.487, count = 2 },
    textField  = { position = { -0.02, 0.25, -0.35 }, width = 890 }
  },
  [4] = { checkboxes = { posZ = -0.239, count = 3 } },
  [5] = { checkboxes = { posZ = 0.309, count = 4 } },
  [6] = { checkboxes = { posZ = 0.856, count = 5 } },
}
require("playercards/customizable/UpgradeSheetLibrary")
