boxSize        = 40
xInitial       = -0.981
xOffset        = 0.061
customizations = {
  [1] = { checkboxes = { posZ = -0.955, count = 2 } },
  [2] = { checkboxes = { posZ = -0.698, count = 2 } },
  [3] = { checkboxes = { posZ = -0.275, count = 2 } },
  [4] = { checkboxes = { posZ = 0.229, count = 2 } },
  [5] = { checkboxes = { posZ = 0.650, count = 2 } },
  [6] = { checkboxes = { posZ = 1.075, count = 4 } },
  [7] = { checkboxes = { posZ = 1.250, count = 4 } }
}
require("playercards/customizable/UpgradeSheetLibrary")
