-- Campaign Log: The Path to Carcosa 2
defaultButtonData = {
  checkbox = {
    --1 checkbox
    { pos = { -0.69, 0.11, -0.146 } },

    --2 checkbox
    { pos = { -0.67, 0.11, -0.049 } },

    --3 checkbox
    { pos = { -0.646, 0.11, 0.144 } },

    --4 checkbox
    { pos = { -0.625, 0.11, 0.236 } },

    --5 checkbox
    { pos = { -0.61, 0.11, 0.42 } },

    --6 checkbox
    { pos = { -0.59, 0.11, 0.51 } },

    --7 checkbox
    { pos = { -0.575, 0.11, 0.605 } },

    --8 checkbox
    { pos = { -0.560, 0.11, 0.70 } }
  },
  counter = {},
  textbox = {
    --Campaign Notes
    {
      pos       = { 0.5, 0.11, -0.637 },
      rows      = 6,
      width     = 3500,
      font_size = 200
    }
  }
}

require("CampaignLogLibrary")