-- Campaign Log: The Scarlet Keys 2
interfaceScale    = { 0.13, 0.1, 0.13 }
defaultButtonData = {
  checkbox = {},
  counter = {},
  textbox = {
    -- San Juan
    {
      pos   = { -0.72, 0.11, -1.40 },
      rot   = { 0, -6, 0 },
      width = 1000
    },
    -- Quito
    {
      pos   = { -0.86, 0.11, -0.915 },
      rot   = { 0, -19, 0 },
      width = 1000
    },
    -- Reykjavik
    {
      pos   = { 0.23, 0.11, -1.17 },
      rot   = { 0, -6, 0 },
      width = 1000
    },
    -- London
    {
      pos   = { 0.56, 0.11, -0.88 },
      rot   = { 0, 5, 0 },
      width = 1000
    },
    -- Hong Kong
    {
      pos   = { -0.51, 0.11, -0.1 },
      rot   = { 0, -3, 0 },
      width = 1000
    },
    -- Kuala Lumpur
    {
      pos   = { -0.9, 0.11, 0.33 },
      rot   = { 0, 9, 0 },
      width = 1000
    },
    -- Manokwari
    {
      pos   = { -0.13, 0.11, 0.57 },
      rot   = { 0, 14, 0 },
      width = 1000
    },
    -- Tunguska
    {
      pos   = { 0.9, 0.11, 0.01 },
      rot   = { 0, -16, 0 },
      width = 1000
    },
    -- Kabul
    {
      pos = { 0.51, 0.11, 0.65 },
      rot = { 0, -4, 0 },
      width = 1000
    },
    -- killed investigators
    {
      pos       = { -0.7, 0.11, 1.75 },
      rot       = { 0, 3, 0 },
      rows      = 9,
      width     = 4500,
      font_size = 200
    }
  }
}

require("CampaignLogLibrary")