local DeckLib         = require("util/DeckLib")
local PlayermatApi    = require("playermat/PlayermatApi")
local Zones           = require("playermat/Zones")

local VALID_MATCOLORS = {
  White  = true,
  Orange = true,
  Green  = true,
  Red    = true
}

local lastprocessedCard

function onLoad()
  self.UI.setXmlTable({
    {
      tag = "Button",
      attributes = {
        onClick  = "markPlayerCards",
        position = "0 0 -11",
        scale    = "0.1 0.1 1",
        width    = 1000,
        height   = 1000,
        text     = "Mark Player Cards"
      }
    }
  })
end

function markPlayerCards()
  for matColor, _ in pairs(VALID_MATCOLORS) do
    for _, obj in ipairs(PlayermatApi.searchAroundPlayermat(matColor, "isCardOrDeck")) do
      if obj.type == "Card" then
        obj.setMemo(matColor)
      elseif obj.type == "Deck" then
        local data = obj.getData()
        for _, cardData in ipairs(data.ContainedObjects) do
          cardData.Memo = matColor
        end
        obj.destruct()
        spawnObjectData({ data = data })
      end
    end
  end
end

function readMark(card)
  local matColor = card.getMemo()
  if VALID_MATCOLORS[matColor] then
    return matColor
  end
end

function onCollisionEnter(collisionInfo)
  local obj = collisionInfo.collision_object
  if obj.type ~= "Card" or obj == lastprocessedCard then return end
  lastprocessedCard = obj

  Wait.time(function()
    if lastProcessedCard == obj then
      lastProcessedCard = nil
    end
  end, 0.25)

  local matColor = readMark(obj)
  if matColor then
    placeCardBelowPlayerDeck(obj, matColor)
  else
    broadcastToAll("Can't determine owner for this card.")
  end
end

function placeCardBelowPlayerDeck(card, matColor)
  local pos = Zones.getZonePosition(matColor, "Deck"):setAt("y", 3)
  local rot = Zones.getDefaultCardRotation(matColor, "Deck")
  DeckLib.placeOrMergeIntoDeck(card, pos, rot, true)
end
