function onDrop()
  self.setVectorLines({})
  local helper = findHelper()

  if not helper or targetLocation == nil or colorIndex == nil then return end

  helper.call("removeBorder", { location = targetLocation, colorIndex = colorIndex })
  targetLocation = nil
  colorIndex = nil
end

function findHelper()
  for _, obj in ipairs(getObjects()) do
    if obj.getName() == "Undimensioned and Unseen Helper" then
      return obj
    end
  end
end
