function onDrop()
  if helperGuid == nil or targetLocation == nil or colorIndex == nil then return end
  self.setVectorLines({})

  local helper = getObjectFromGUID(helperGuid)
  helper.call("removeBorder", { location = targetLocation, colorIndex = colorIndex })
  targetLocation = nil
  colorIndex = nil
end

function onLoad(savedData)
  if savedData ~= nil and savedData ~= "" then
    helperGuid = JSON.decode(savedData)
  end
end

function onSave()
  return JSON.encode(helperGuid)
end
