-- Campaign Log: Dark Matter
defaultButtonData = {
  checkbox = {
    { pos = { 0.375, 0.11, 0.035 } },
    { pos = { 0.540, 0.11, 0.065 } },
    { pos = { 0.605, 0.11, 0.12 } },
    { pos = { 0.545, 0.11, 0.25 } },
    { pos = { 0.55, 0.11, 0.29 } },
    { pos = { 0.552, 0.11, 0.335 } },
    { pos = { 0.565, 0.11, 0.42 } },
    { pos = { 0.55, 0.11, 0.51 } },
    { pos = { 0.555, 0.11, 0.555 } },
    { pos = { 0.56, 0.11, 0.60 } }
  },
  counter = {
    --Slot one counter 1
    { pos = { -0.57, 0.11, -0.41 },   size = 300 },

    --Slot one counter 2
    { pos = { -0.45, 0.11, -0.41 },   size = 300 },

    --Slot one xp 1
    { pos = { -0.47, 0.11, -0.495 },  size = 300 },

    --Slot two counter 1
    { pos = { -0.16, 0.11, -0.41 },   size = 300 },

    --Slot two counter 2
    { pos = { -0.03, 0.11, -0.41 },   size = 300 },

    --Slot two xp 1
    { pos = { -0.045, 0.11, -0.495 }, size = 300 },

    --Slot three counter 1
    { pos = { -0.58, 0.11, 0.12 },    size = 300 },

    --Slot three counter 2
    { pos = { -0.45, 0.11, 0.12 },    size = 300 },

    --Slot three xp 1
    { pos = { -0.465, 0.11, 0.041 },  size = 300 },

    --Slot four counter 1
    { pos = { -0.17, 0.11, 0.12 },    size = 300 },

    --Slot four counter 2
    { pos = { -0.030, 0.11, 0.12 },   size = 300 },

    --Slot four xp 1
    { pos = { -0.045, 0.11, 0.041 },  size = 300 },

    --Slot one Memories
    { pos = { -0.59, 0.11, -0.325 },  size = 300 },

    --Slot two Memories
    { pos = { -0.175, 0.11, -0.325 }, size = 300 },

    --Slot three Memories
    { pos = { -0.59, 0.11, 0.212 },   size = 300 },

    --Slot four Memories
    { pos = { -0.175, 0.11, 0.21 },   size = 300 },

    --Impending Doom
    { pos = { -0.71, 0.11, 0.72 },    size = 800 }
  },
  textbox = {
    --Slot one player
    {
      pos       = { -0.595, 0.11, -0.617 },
      width     = 1900,
      font_size = 150
    },
    --Slot one investigator
    {
      pos       = { -0.595, 0.11, -0.552 },
      width     = 1900,
      font_size = 150
    },
    --Slot one story
    {
      pos       = { -0.595, 0.11, -0.208 },
      rows      = 4,
      width     = 1900,
      font_size = 150
    },
    --Slot two player
    {
      pos       = { -0.19, 0.11, -0.617 },
      width     = 1900,
      font_size = 150
    },
    --Slot two investigator
    {
      pos       = { -0.19, 0.11, -0.552 },
      width     = 1900,
      font_size = 150
    },
    --Slot two story
    {
      pos       = { -0.19, 0.11, -0.209 },
      rows      = 4,
      width     = 1900,
      font_size = 150
    },
    --Slot three player
    {
      pos       = { -0.595, 0.11, -0.083 },
      width     = 1900,
      font_size = 150
    },
    --Slot three investigator
    {
      pos       = { -0.595, 0.11, -0.017 },
      width     = 1900,
      font_size = 150
    },
    --Slot three story
    {
      pos       = { -0.596, 0.11, 0.325 },
      rows      = 4,
      width     = 1900,
      font_size = 150
    },
    --Slot four player
    {
      pos       = { -0.19, 0.11, -0.084 },
      width     = 1900,
      font_size = 150
    },
    --Slot four investigator
    {
      pos       = { -0.19, 0.11, -0.018 },
      width     = 1900,
      font_size = 150
    },
    --Slot four story
    {
      pos       = { -0.19, 0.11, 0.325 },
      rows      = 4,
      width     = 1900,
      font_size = 150
    },
    --Killed Textbox
    {
      pos   = { 0.435, 0.11, 0.795 },
      rot   = { 0, -7.5, 0 },
      rows  = 3,
      width = 3000
    },
    --Campaign Notes
    {
      pos       = { 0.42, 0.11, -0.42 },
      rows      = 18,
      width     = 3200,
      font_size = 150
    }
  }
}

require("CampaignLogLibrary")
