-- Campaign Log: Edge of the Earth 1
interfaceScale    = { 0.09, 0.1, 0.09 }
defaultButtonData = {
  checkbox = {
    --Ice and Death
    { pos = { -0.52, 0.11, 0.13 } },

    --Part 1
    { pos = { -0.452, 0.11, 0.198 } },

    --Part 2
    { pos = { -0.33, 0.11, 0.182 } },

    --Part 3
    { pos = { -0.2, 0.11, 0.165 } },

    --To the Forbidden Peaks
    { pos = { -0.505, 0.11, 0.28 } },

    --City of Elder Things
    { pos = { -0.49, 0.11, 0.4 } },

    --The Heart of Madness
    { pos = { -0.47, 0.11, 0.54 } },

    --Part 1
    { pos = { -0.41, 0.11, 0.60 } },

    --Part 2
    { pos = { -0.26, 0.11, 0.58 } },

    --Fatal Mirage 1
    { pos = { -0.53, 0.11, 0.69 } },

    --Fatal Mirage 2
    { pos = { -0.493, 0.11, 0.68 } },

    --Fatal Mirage 3
    { pos = { -0.445, 0.11, 0.67 } }
  },
  counter = {
    --Slot one counter 1
    { pos = { -0.5, 0.11, -0.43 } },

    --Slot one counter 2
    { pos = { -0.37, 0.11, -0.43 } },

    --Slot one xp 1
    { pos = { -0.37, 0.11, -0.505 } },

    --Slot two counter 1
    { pos = { -0.18, 0.11, -0.425 } },

    --Slot two counter 2
    { pos = { -0.04, 0.11, -0.425 } },

    --Slot two xp 1
    { pos = { -0.04, 0.11, -0.505 } },

    --Slot three counter 1
    { pos = { 0.15, 0.11, -0.42 } },

    --Slot three counter 2
    { pos = { 0.27, 0.11, -0.42 } },

    --Slot three xp 1
    { pos = { 0.27, 0.11, -0.505 } },

    --Slot four counter 1
    { pos = { 0.47, 0.11, -0.42 } },

    --Slot four counter 2
    { pos = { 0.6, 0.11, -0.425 } },

    --Slot four xp 1
    { pos = { 0.6, 0.11, -0.505 } }
  },
  textbox = {
    --Slot one player
    {
      pos       = { -0.50, 0.11, -0.645 },
      width     = 1500,
      font_size = 150
    },
    --Slot one investigator
    {
      pos       = { -0.50, 0.11, -0.575 },
      width     = 1500,
      font_size = 150
    },
    --Slot one story
    {
      pos       = { -0.50, 0.11, -0.27 },
      rows      = 9,
      width     = 1500,
      font_size = 100
    },
    --Slot two player
    {
      pos       = { -0.18, 0.11, -0.645 },
      width     = 1500,
      font_size = 150
    },
    --Slot two investigator
    {
      pos       = { -0.178, 0.11, -0.575 },
      width     = 1500,
      font_size = 150
    },
    --Slot two story
    {
      pos       = { -0.178, 0.11, -0.27 },
      rows      = 9,
      width     = 1500,
      font_size = 100
    },
    --Slot three player
    {
      pos       = { 0.145, 0.11, -0.640 },
      width     = 1500,
      font_size = 150
    },
    --Slot three investigator
    {
      pos       = { 0.145, 0.11, -0.570 },
      width     = 1500,
      font_size = 150
    },
    --Slot three story
    {
      pos       = { 0.145, 0.11, -0.268 },
      rows      = 9,
      width     = 1500,
      font_size = 100
    },
    --Slot four player
    {
      pos       = { 0.47, 0.11, -0.64 },
      width     = 1500,
      font_size = 150
    },
    --Slot four investigator
    {
      pos       = { 0.47, 0.11, -0.565 },
      width     = 1500,
      font_size = 150
    },
    --Slot four story
    {
      pos       = { 0.47, 0.11, -0.268 },
      rows      = 9,
      width     = 1500,
      font_size = 100
    },

    --Campaign Notes
    {
      pos       = { 0.449, 0.11, 0.26 },
      rot       = { 0, 1, 0 },
      rows      = 18,
      width     = 2500,
      font_size = 150
    },
    --Killed and Insane
    {
      pos       = { 0.21, 0.11, 0.82 },
      rot       = { 0, 1.75, 0 },
      rows      = 5,
      width     = 1800,
      font_size = 150
    },
    --Chaos Bag
    {
      pos       = { 0.55, 0.11, 0.730 },
      rows      = 8,
      width     = 1000,
      font_size = 150
    }
  }
}