-- Campaign Log: The Innsmouth Conspiracy 1
defaultButtonData = {
  checkbox = {},
  checkbox = {},
  counter = {
    --Slot one counter 1
    { pos = { -0.7, 0.11, -0.44 } },

    --Slot one counter 2
    { pos = { -0.51, 0.11, -0.44 } },

    --Slot one xp 1
    { pos = { -0.510, 0.11, -0.544 } },

    --Slot two counter 1
    { pos = { -0.274, 0.11, -0.44 } },

    --Slot two counter 2
    { pos = { -0.06, 0.11, -0.44 } },

    --Slot two xp 1
    { pos = { -0.061, 0.11, -0.54 } },

    --Slot three counter 1
    { pos = { 0.15, 0.11, -0.44 } },

    --Slot three counter 2
    { pos = { 0.379, 0.11, -0.44 } },

    --Slot three xp 1
    { pos = { 0.38, 0.11, -0.54 } },

    --Slot four counter 1
    { pos = { 0.614, 0.11, -0.43 } },

    --Slot four counter 2
    { pos = { 0.82, 0.11, -0.43 } },

    --Slot four xp 1
    { pos = { 0.827, 0.11, -0.535 } }
  },
  textbox = {
    --Slot one player
    {
      pos       = { -0.64, 0.11, -0.70 },
      width     = 2000,
      font_size = 150
    },
    --Slot one investigator
    {
      pos       = { -0.64, 0.11, -0.615 },
      width     = 2000,
      font_size = 150
    },
    --Slot one story
    {
      pos       = { -0.64, 0.11, -0.23 },
      rows      = 9,
      width     = 2000,
      font_size = 100
    },
    --Slot two player
    {
      pos       = { -0.2, 0.11, -0.7 },
      width     = 2000,
      font_size = 150
    },
    --Slot two investigator
    {
      pos       = { -0.2, 0.11, -0.615 },
      width     = 2000,
      font_size = 150
    },
    --Slot two story
    {
      pos       = { -0.2, 0.11, -0.23 },
      rows      = 9,
      width     = 2000,
      font_size = 100
    },
    --Slot three player
    {
      pos       = { 0.241, 0.11, -0.694 },
      width     = 2000,
      font_size = 150
    },
    --Slot three investigator
    {
      pos       = { 0.24, 0.11, -0.613 },
      width     = 2000,
      font_size = 150
    },
    --Slot three story
    {
      pos       = { 0.24, 0.11, -0.228 },
      rows      = 9,
      width     = 2000,
      font_size = 100
    },
    --Slot four player
    {
      pos       = { 0.69, 0.11, -0.69 },
      width     = 2000,
      font_size = 150
    },
    --Slot four investigator
    {
      pos       = { 0.69, 0.11, -0.609 },
      width     = 2000,
      font_size = 150
    },
    --Slot four story
    {
      pos       = { 0.671, 0.11, -0.227 },
      rows      = 9,
      width     = 2000,
      font_size = 100
    },
    --Memories Recovered
    {
      pos       = { 0.44, 0.11, 0.325 },
      rows      = 14,
      width     = 3500,
      font_size = 200
    },
    --Campaign Notes 1
    {
      pos       = { -0.43, 0.11, 0.33 },
      rows      = 14,
      width     = 3500,
      font_size = 200
    },
    --Campaign Notes 2
    {
      pos       = { -0.478, 0.11, 0.8 },
      rows      = 8,
      width     = 3000,
      font_size = 150
    },
    --Killed and Insane
    {
      pos       = { 0.448, 0.11, 0.887 },
      rows      = 5,
      width     = 4000,
      font_size = 150
    }
  }
}

require("CampaignLogLibrary")