-- Campaign Log: The Feast of Hemlock Vale 2
interfaceScale    = { 0.15, 0.1, 0.15 }
defaultButtonData = {
  checkbox = {},
  counter = {},
   textbox = {
    -- Madre
    {
      pos   = { -0.69, 0.11, -1.56 },
      rot   = { 0, -3, 0 },
      rows  = 10,
      width = 3000
    },
    -- Leah
    {
      pos   = { 0.79, 0.11, -1.52},
      rot   = { 0, 3, 0 },
      rows  = 10,
      width = 3000
    },
    -- Simeon
    {
      pos   = { -0.69, 0.11, -0.655 },
      rot   = { 0, -1, 0 },
      rows  = 10,
      width = 3000
    },
    -- William
    {
      pos   = { 0.82, 0.11, -0.58 },
      rot   = { 0, -2, 0 },
      rows  = 10,
      width = 3000
    },
    -- River
    {
      pos   = { -0.60, 0.11, 0.47 },
      rot   = { 0, 0, 0 },
      rows  = 10,
      width = 3000
    },
    -- Gideon
    {
      pos   = { 0.79, 0.11, 0.385 },
      rot   = { 0, 0, 0 },
      rows  = 10,
      width = 3000
    },
    -- Judith
    {
      pos   = { -0.76, 0.11, 1.56 },
      rot   = { 0, -1, 0 },
      rows  = 10,
      width = 3000
    },
    -- Theo
    {
      pos   = { 0.6, 0.11, 1.23 },
      rot   = { 0, 2, 0 },
      rows  = 10,
      width = 3000
    }
  }
}

function createCampaignSpecificStuff()
  createDataForRelationships()
end

function createDataForRelationships()
  -- checkboxes for relationship level
  local rlPos = {
    madre   = {
      startPos = Vector(-0.64, 0.06, -1.23),
      boxCount = 6
    },
    leah    = {
      startPos = Vector(0.82, 0.06, -1.18),
      boxCount = 6
    },
    simeon  = {
      startPos = Vector(-0.62, 0.06, -0.31),
      boxCount = 6
    },
    william = {
      startPos = Vector(0.95, 0.06, -0.25),
      boxCount = 6
    },
    river   = {
      startPos = Vector(-0.67, 0.06, 0.815),
      boxCount = 6
    },
    gideon  = {
      startPos = Vector(0.89, 0.06, 0.71),
      boxCount = 6
    },
    judith  = {
      startPos = Vector(-0.772, 0.06, 1.90),
      boxCount = 7
    },
    theo    = {
      startPos = Vector(0.475, 0.06, 1.58),
      boxCount = 7
    }
  }
  for _, char in pairs(rlPos) do
    for i = 0, (char.boxCount - 1) do
      local random_degree = math.random(-5, 5)
      local random_size = math.random(90, 110) / 100
      local cb_tbl = {
        pos = { char.startPos.x + i * 0.0657, char.startPos.y, char.startPos.z },
        rot = { 0, 3 + random_degree, 0 },
        size = 300 * random_size
      }
      table.insert(defaultButtonData.checkbox, cb_tbl)
    end
  end
end

require("CampaignLogLibrary")