local GUIDReferenceApi = require("core/GUIDReferenceApi")
local SearchLib        = require("util/SearchLib")

SOLUTION_POSITION      = { 1.15, .127, -0.515 }

function onLoad()
  self.createButton({
    label          = "Set Up",
    click_function = "setup",
    function_owner = self,
    position       = { 0, 0.1, 0 },
    height         = 120,
    width          = 400,
    scale          = { x = 1.75, y = 1.75, z = 1.75 },
    font_size      = 100
  })

  suspectDeck = getObjectFromGUID("360107")
  hideoutDeck = getObjectFromGUID("f3ec1a")
end

function setup()
  local mythosArea = GUIDReferenceApi.getObjectByOwnerAndType("Mythos", "MythosArea")
  if SETUP_DONE then return end
  SETUP_DONE = true

  suspectDeck.shuffle()
  hideoutDeck.shuffle()

  local takeParams = {
    position = mythosArea.positionToWorld(SOLUTION_POSITION),
    rotation = mythosArea.getRotation():setAt("z", 180),
    smooth   = false
  }
  suspectDeck.takeObject(takeParams)
  hideoutDeck.takeObject(takeParams)

  -- get solutions and rename
  Wait.time(function()
    local searchResult = SearchLib.atPosition(mythosArea.positionToWorld(SOLUTION_POSITION), "isCardOrDeck")
    if #searchResult == 1 then
      searchResult[1].setName("Solutions")
    end
  end, 1)

  suspectDeck.setPosition(hideoutDeck.getPosition() + Vector(0, 1, 0))
  Wait.time(function()
    hideoutDeck.shuffle()
    hideoutDeck.setName("Leads Deck")
  end, 1)
end
