VALID_TOKENS    = {
  ["Blood"] = true
}

MAX_SEALED      = 3
hasXML          = true
isHelperEnabled = true

require("playercards/CardsThatSealTokens")
require("playercards/CardsWithHelper")
local ChaosBagApi          = require("chaosbag/ChaosBagApi")
local helpVisibleToPlayers = {}

function getSaveData()
  return { isHelperEnabled = isHelperEnabled, loopId = loopId }
end

function onLoad2(loadedData)
  if loadedData then
    isHelperEnabled = loadedData.isHelperEnabled or true
    loopId          = loadedData.loopId
  end

  createHelperXML()

  ---@diagnostic disable-next-line: undefined-global
  updateDisplay()
end

function generateDefaults(buttonCount)
  local defaults = {
    tag = "Defaults",
    children = {
      {
        tag = "Button",
        attributes = {
          font      = "font_teutonic-arkham",
          fontSize  = 275,
          color     = "#77674DE6",
          textColor = "White"
        }
      },
      {
        tag = "TableLayout",
        attributes = {
          class               = "button",
          position            = "180 -3 -10",
          rotation            = "0 0 180",
          height              = buttonCount * 500,
          width               = 1550,
          scale               = "0.1 0.1 1",
          cellSpacing         = 65,
          cellPadding         = "0 6 6 6",
          cellBackgroundColor = "rgba(1,1,1,0)",
          rowBackgroundColor  = "rgba(0,0,0,0.666)"
        }
      }
    }
  }
  return defaults
end

function createHelperXML()
  -- create the XML table
  local buttonLabels     = { "Seal From Bag", "Seal From Play", "Release Token" }
  local onClickFunctions = { "xml_sealToken", "triggerXMLTokenLabelCreation", "xml_releaseToken" }
  local xmlTable         = {}

  -- get the defaults
  table.insert(xmlTable, generateDefaults(3))

  -- create the table layout
  local tableLayoutXml = {
    tag        = "TableLayout",
    attributes = { class = "button", id = "Helper", active = "false" },
    children   = {}
  }

  -- add the buttons to it
  for i = 1, 3 do
    local buttonXml = {
      tag = "Row",
      attributes = { id = "Row" .. i },
      children = {
        {
          tag = "Cell",
          children = {
            {
              tag = "Button",
              attributes = {
                id      = ("Button" .. i),
                text    = buttonLabels[i],
                onClick = onClickFunctions[i]
              }
            }
          }
        }
      }
    }

    table.insert(tableLayoutXml.children, buttonXml)
  end

  -- add to the XmlTable
  table.insert(xmlTable, tableLayoutXml)

  addTokenRules(xmlTable)
end

function addTokenRules(xmlTable)
  local tokenRulesXml = {
    tag = "Panel",
    attributes = {
      id        = "rulesPanel",
      width     = 2100,
      height    = 1500,
      rotation  = "0 0 180",
      color     = "#404040",
      textColor = "White",
      position  = "-210 0 -5",
      active    = false,
      scale     = "0.1 0.1 1"
    },
    children = {
      {
        tag = "Tablelayout",
        attributes = {
          width              = 1950,
          height             = 1350,
          position           = "0 0 0",
          rowBackgroundColor = "#D4B889",
          cellPadding        = "10 10 10 10"
        },
        children = {
          {
            tag = "Row",
            attributes = { preferredheight = 210 },
            children = {
              tag = "Cell",
              children = {
                tag = "Text",
                attributes = {
                  fontsize = 180,
                  font     = "font_teutonic-arkham",
                  text     = "Blood Token Rules Reminder"
                }
              }
            }
          },
          {
            tag = "Row",
            attributes = { color = "#cfcfcf" },
            children = {
              tag = "Cell",
              children = {
                tag = "Text",
                attributes = {
                  fontsize = 100,
                  text     =
                  "Blood Tokens revealed during a skill test have the following effect: \"-1. Reveal another token. If this skill test fails, seal 1 Blood token revealed during this test on your investigator card.\""
                }
              }
            }
          },
          {
            tag = "Row",
            attributes = { color = "#cfcfcf" },
            children = {
              tag = "Cell",
              attributes = { color = "#D4B889" },
              children = {
                tag = "Text",
                attributes = {
                  fontsize = 100,
                  text     = "Each additional revealed Blood token has the following effect: \"-1. Reveal another token.\""
                }
              }
            }
          },
          {
            tag = "Row",
            attributes = { color = "#cfcfcf" },
            children = {
              tag = "Cell",
              attributes = { color = "#D4B889" },
              children = {
                tag = "Text",
                attributes = {
                  fontsize = 100,
                  text     =
                  "No more than a total of three Blood tokens can be sealed on a single investigator at any given time."
                }
              }
            }
          }
        }
      }
    }
  }

  table.insert(xmlTable, tokenRulesXml)

  -- add help button
  local helpButtonXml = {
    tag = "Panel",
    attributes = {
      width    = 86,
      height   = 86,
      rotation = "0 0 180",
      position = "0 83.5 -12",
      scale    = "0.24 0.24 1"
    },
    children = {
      tag        = "Button",
      attributes = { fontSize = 80, onClick = "toggleRules", text = "?" }
    }
  }
  table.insert(xmlTable, helpButtonXml)
  self.UI.setXmlTable(xmlTable)
end

function triggerXMLTokenLabelCreation(player)
  ChaosBagApi.removeTokenFromPlay("seal", VALID_TOKENS, nil, nil, nil, self.getGUID(), player.color)
end

function sealTokenWrapper(params)
  sealToken("Blood", params.playerColor)
end

function xml_sealToken(player)
  sealToken("Blood", player.color)
end

function xml_releaseToken(player)
  releaseOneToken(player.color)
end

function toggleRules(player)
  if helpVisibleToPlayers[player.color] then
    helpVisibleToPlayers[player.color] = nil
  else
    helpVisibleToPlayers[player.color] = true
  end
  updateRulesVisibility()
end

-- updates the visibility of the rules text
function updateRulesVisibility()
  local visibility = ""
  for playerColor, _ in pairs(helpVisibleToPlayers) do
    if string.len(visibility) > 0 then
      visibility = visibility .. "|" .. playerColor
    else
      visibility = playerColor
    end
  end
  self.UI.setAttribute("rulesPanel", "visibility", visibility)
  self.UI.setAttribute("rulesPanel", "active", string.len(visibility) > 0)
end
