-- Campaign Log: Children of Blood
interfaceScale    = { 0.13, 0.13, 0.13 }
defaultButtonData = { checkbox = {}, counter = {}, textbox = {} }
checkboxFontColor = { 0.55, 0.03, 0.03, 98 }

-- Helper to fill player slots
ROW_DATA          = {
  name         = -1.525,
  investigator = -1.335,
  xp           = -1.14,
  trauma       = -0.9,
  earned       = -0.515
}
PLAYER_DATA       = {
  name         = -0.9,
  investigator = -0.9,
  xp           = -0.7,
  pTrauma      = -1.05,
  mTrauma      = -0.75,
  earned       = -0.9
}

function createCampaignSpecificStuff()
  -- Add player stuff first to achieve expected orders
  local pRot = { 0, -0.3, 0 }
  for i = 1, 4 do
    local xOffset = 0.591 * (i - 1)
    local zOffset = 0.002 * (i - 1)

    -- Add Counters (Trauma & Experience)
    table.insert(defaultButtonData.counter, {
      pos = { PLAYER_DATA.pTrauma + xOffset, 0.11, ROW_DATA.trauma + zOffset },
      rot = pRot
    })
    table.insert(defaultButtonData.counter, {
      pos = { PLAYER_DATA.mTrauma + xOffset, 0.11, ROW_DATA.trauma + zOffset },
      rot = pRot
    })
    table.insert(defaultButtonData.counter, {
      pos = { PLAYER_DATA.xp + xOffset, 0.11, ROW_DATA.xp + zOffset },
      rot = pRot
    })

    -- Add Textboxes (Player, Investigator, Earned Assets / Weaknesses)
    table.insert(defaultButtonData.textbox, {
      pos       = { PLAYER_DATA.name + xOffset, 0.11, ROW_DATA.name + zOffset },
      rot       = pRot,
      width     = 2000,
      font_size = 230
    })
    table.insert(defaultButtonData.textbox, {
      pos       = { PLAYER_DATA.investigator + xOffset, 0.11, ROW_DATA.investigator + zOffset },
      rot       = pRot,
      width     = 2000,
      font_size = 230
    })
    table.insert(defaultButtonData.textbox, {
      pos       = { PLAYER_DATA.earned + xOffset, 0.11, ROW_DATA.earned + zOffset },
      rot       = pRot,
      rows      = 6,
      width     = 1900,
      font_size = 190
    })
  end

  -- Scenario Completion Checkboxes
  table.insert(defaultButtonData.checkbox, { pos = { -1.12, 0.11, 0.25 }, rot = { 0, -5, 0 }, size = 800 })  -- River of Blood
  table.insert(defaultButtonData.checkbox, { pos = { -1.095, 0.11, 0.65 }, rot = { 0, -5, 0 }, size = 800 }) -- New Horizons
  table.insert(defaultButtonData.checkbox, { pos = { -1.075, 0.11, 1.04 }, rot = { 0, -5, 0 }, size = 800 }) -- Blood Money

  -- Scenario XP Counters
  table.insert(defaultButtonData.counter, { pos = { -0.33, 0.11, 0.372 }, rot = { 0, -5, 0 }, size = 500 })  -- River of Blood
  table.insert(defaultButtonData.counter, { pos = { -0.305, 0.11, 0.765 }, rot = { 0, -5, 0 }, size = 500 }) -- New Horizons
  table.insert(defaultButtonData.counter, { pos = { -0.28, 0.11, 1.157 }, rot = { 0, -5, 0 }, size = 500 })  -- Blood Money

  -- Unique Textboxes
  table.insert(defaultButtonData.textbox, { -- Killed
    pos       = { -0.344, 0.11, 1.73 },
    rot       = { 0, 0.35, 0 },
    rows      = 6,
    width     = 4600,
    font_size = 270
  })
  table.insert(defaultButtonData.textbox, { -- Notes
    pos       = { 0.66, 0.11, 0.54 },
    rot       = { 0, 5, 0 },
    rows      = 15,
    width     = 4100,
    font_size = 250
  })
  table.insert(defaultButtonData.textbox, { -- Chaos Bag
    pos       = { 0.86, 0.11, 1.7 },
    rot       = { 0, 3.5, 0 },
    rows      = 7,
    width     = 2175,
    font_size = 265
  })
end

require("CampaignLogLibrary")
