local CoroutineLib     = require("util/CoroutineLib")
local DeckLib          = require("util/DeckLib")
local GUIDReferenceApi = require("core/GUIDReferenceApi")
local MythosAreaApi    = require("mythos/MythosAreaApi")
local PlayAreaApi      = require("playarea/PlayAreaApi")
local PlayermatApi     = require("playermat/PlayermatApi")
local TableLib         = require("util/TableLib")

local LOCATION_GRIDS   = {
  -- Waterfront Warehouse
  ["13020"] = { 0, 2 },
  ["13021"] = { 0, 2 },

  -- Garrison Street
  [""] = { -1, 1 },
  [""] = { -1, 1 },

  -- Water Street
  ["13008"] = { 1, 1 },
  ["13009"] = { 1, 1 },

  -- Erwin Bridge
  [""] = { 0, 0 },
  [""] = { 0, 0 },

  -- Unvisited Isle
  [""] = { -1, 0 },
  [""] = { -1, 0 },

  -- River Docks
  [""] = { -1, -1 },
  [""] = { -1, -1 },

  -- Main Street
  [""] = { 1, -1 },
  [""] = { 1, -1 },

  -- Back Alley
  ["13022"] = { 0, -2 },
  ["13023"] = { 0, -2 }
}

local LAIR_GRIDS       = { { 0, 2 }, { -1, 0 }, { 0, -2 } }
local trash            = GUIDReferenceApi.getObjectByOwnerAndType("Mythos", "Trash")

function showOptionsDialogAndWait(player, title, options, default)
  local result
  player.showOptionsDialog(
    title,
    options,
    default,
    function(value) result = value end
  )
  CoroutineLib.yieldCondition(function() return result ~= nil end)
  return result
end

function onLoad()
  self.createButton({
    label          = "Set Up",
    click_function = "setup",
    function_owner = self,
    position       = { 0, 0.11, 0 },
    height         = 160,
    width          = 500,
    scale          = { x = 1.75, y = 1.75, z = 1.75 },
    font_size      = 90
  })
end

function setup(_, playerColor)
  local player = Player[playerColor]

  local function setupCoroutine()
    -- Ask for difficulty
    local difficulty = showOptionsDialogAndWait(
      player,
      "Choose Difficulty:",
      { "Easy", "Standard", "Hard", "Export" },
      "Standard"
    )

    -- Ask for investigator count
    local investigatorCount = showOptionsDialogAndWait(
      player,
      "Choose Investigator Count:",
      { 1, 2, 3, 4 },
      PlayAreaApi.getInvestigatorCount()
    )

    -- Gather all relevant encounter sets
    -- (except for Infected, which is separately handled because it's fully set aside)
    local listOfSets = {
      -- CoB sets
      "River of Blood", "Blood Blight", "Blood Moon", "Children of Blood", "Hunted", "Misinformation",
      -- Core 2026 sets
      "Dead Ends", "Flying Terrors"
    }

    -- Adjust the list based on difficulty
    if difficulty == "Hard" or difficulty == "Expert" then
      table.insert(listOfSets, "Agents of Zburamoarte")
      table.insert(listOfSets, "Mongrels")
    else
      table.insert(listOfSets, "Preyed Upon")
      table.insert(listOfSets, "Vermin")
    end

    -- Adjust the list based on investigator count
    if investigatorCount >= 3 then
      table.insert(listOfSets, "Afflicted")
    end

    -- Get reference to card source
    local objList = getObjectsWithTag("CoB-Cards")
    if #objList == 0 then
      broadcastToAll("Couldn't find campaign card source!", "Red")
      return
    end

    local CardSource           = objList[1]
    local setAsideObjects      = {}
    local encounterDeckObjects = {}
    local mapSetAside          = {
      ["13110"] = true, -- Night Feeder
      [""] = true,      -- Spawn of Zburamoarte
      [""] = true,      -- Detective Reynolds
      [""] = true,      -- Fang of Zburamoarte
    }
    local mapRFG               = {
      ["13024"] = true, -- Julia Stern
      ["13025"] = true, -- Julia Stern
      ["13026"] = true, -- Julia Stern
    }

    -- Determine proper version of Julia Stern
    local JULIA_IDS            = {
      Easy     = "13024",
      Standard = "13025",
      Hard     = "13026",
      Expert   = "13026",
    }
    local juliaId              = JULIA_IDS[difficulty]

    -- Get card list (each card has a data and metadata field)
    local cardList             = CardSource.call("getCardsForListOfSets", listOfSets)
    printToAll(string.format(
      "Gathered %d cards based on selected difficulty (%s) and player count (%d).",
      #cardList,
      difficulty,
      investigatorCount
    ))

    -- Handling for Civilians
    local civiliansToSpawn = (investigatorCount > 2) and 2 or 1

    -- Handling for Dawn / Dusk locations
    local locationTraitToUse = (difficulty == "Hard" or difficulty == "Expert") and "Dusk" or "Dawn"

    for _, card in ipairs(cardList) do
      local md = card.metadata
      local id = md.id

      -- skip RFG cards
      if not mapRFG[id] then
        if mapSetAside[id] then
          table.insert(setAsideObjects, card.data)
        elseif md.type == "Location" then
          if string.contains(md.traits, locationTraitToUse) then
            spawnCardAtPosition(card.data, PlayAreaApi.gridToWorld(LOCATION_GRIDS[id]))
          end
        elseif id == "13027" then -- Waterfront Civilian
          if civiliansToSpawn == 2 then
            civiliansToSpawn = civiliansToSpawn - 1
            spawnCardAtPosition(card.data, PlayAreaApi.gridToWorld({ -0.5, 1 })) -- at Garrison Street
          elseif civiliansToSpawn == 1 then
            civiliansToSpawn = civiliansToSpawn - 1
            spawnCardAtPosition(card.data, PlayAreaApi.gridToWorld({ 1.5, -1 })) -- at Main Street
          else
            table.insert(setAsideObjects, card.data)
          end
        else
          table.insert(encounterDeckObjects, card.data)
        end
      end
    end

    -- Move mini-cards to Water Street
    local shouldMove = {}
    for _, matColor in ipairs(PlayermatApi.getUsedMatColors()) do
      local miniId = PlayermatApi.getActiveInvestigatorData(matColor).miniId
      shouldMove[miniId] = true
    end

    local movedMiniCount = 0
    local MINI_OFFSET    = {
      Vector(1, 0, 1),
      Vector(-1, 0, 1),
      Vector(-1, 0, -1),
      Vector(1, 0, -1),
    }
    local basePos        = PlayAreaApi.gridToWorld(LOCATION_GRIDS["13008"])
    for _, minicard in ipairs(getObjectsWithTag("MiniCard")) do
      local md = JSON.decode(minicard.getGMNotes())
      if md and md.id and shouldMove[md.id] then
        movedMiniCount = movedMiniCount + 1
        local targetPos = basePos + MINI_OFFSET[movedMiniCount]
        minicard.setPosition(targetPos)
        shouldMove[md.id] = false
      end
    end

    if movedMiniCount > 0 then
      printToAll(string.format("Moved %d mini cards to Water Street.", movedMiniCount))
    end

    -- Shuffle Julia with two random cards
    local lairCardList = {
      getCardById(juliaId).data,
      TableLib.pickRandom(encounterDeckObjects, true),
      TableLib.pickRandom(encounterDeckObjects, true)
    }
    TableLib.shuffle(lairCardList)

    -- Place beneath each Lair location
    for i, cardData in ipairs(lairCardList) do
      local grid = { LAIR_GRIDS[i][1] - 0.5, LAIR_GRIDS[i][2] }
      spawnCardAtPosition(cardData, PlayAreaApi.gridToWorld(grid), Vector(0, 270, 180))
    end
    printToAll("Shuffled Julia Stern with two random cards of the encounter deck and placed those cards beneath the Lair locations.")

    -- Create encounter deck
    local deckPosition   = MythosAreaApi.getEncounterDeckPosition()
    local deckRotation   = MythosAreaApi.getEncounterDiscardRotation()
    local deckdata       = DeckLib.generateDeckDataFromCardList(
      TableLib.shuffle(encounterDeckObjects),
      deckPosition,
      deckRotation
    )
    deckdata["Nickname"] = "Encounter Deck"
    spawnObjectData({ data = deckdata })
    printToAll("Encounter deck created.")

    -- Handle Infected
    local infectedCards = CardSource.call("getCardsForListOfSets", { "Infected" })
    local infectedDeckObjects = {}
    for _, card in ipairs(infectedCards) do
      table.insert(infectedDeckObjects, card.data)
    end
    local infectedDeckData = DeckLib.generateDeckDataFromCardList(
      infectedDeckObjects,
      Vector(0, 0, 0),
      Vector(0, 270, 0)
    )
    infectedDeckData["Nickname"] = "Infected"

    -- Create Set Aside
    table.insert(setAsideObjects, infectedDeckData)
    spawnSetAsideChest(setAsideObjects)
    printToAll("Set aside cards spawned.")

    -- Remove this helper
    trash.putObject(self)
  end

  CoroutineLib.start(setupCoroutine)
end

function spawnCardAtPosition(cardData, position, rotation)
  rotation = rotation or Vector(0, 270, 0)
  cardData.Transform = {
    posX = position.x,
    posY = position.y,
    posZ = position.z,
    rotX = rotation.x,
    rotY = rotation.y,
    rotZ = rotation.z,
    scaleX = 1,
    scaleY = 1,
    scaleZ = 1
  }
  return spawnObjectData({ data = cardData })
end

function spawnSetAsideChest(objects)
  local MythosArea = GUIDReferenceApi.getObjectByOwnerAndType("Mythos", "MythosArea")
  local position   = MythosArea.positionToWorld(Vector(2.191, 0.1, -0.462))
  local rotation   = MythosArea.getRotation() - Vector(0, 45, 0)
  return spawnObjectData({
    data = {
      ColorDiffuse     = { b = 0, g = 0, r = 0 },
      ContainedObjects = objects,
      CustomMesh       = {
        DiffuseURL =
        "https://steamusercontent-a.akamaihd.net/ugc/764975951334960553/C518D80E31E27DB23EEAC8CF9253E59798865790/",
        MaterialIndex = 1,
        MeshURL =
        "https://steamusercontent-a.akamaihd.net/ugc/2038485431565955058/F72FECE5488594A28292C06997A2E28A8B8961C5/",
        NormalURL =
        "https://steamusercontent-a.akamaihd.net/ugc/764975951334960069/E70E4A58A1B7827F1E5E2AF9FF44DF0BD5DA33F7/",
        TypeIndex = 6
      },
      Hands            = false,
      HideWhenFaceDown = false,
      Name             = "Custom_Model_Bag",
      Nickname         = "Set-aside",
      Transform        = {
        posX   = position.x,
        posY   = 1.565,
        posZ   = position.z,
        rotX   = rotation.x,
        rotY   = rotation.y,
        rotZ   = rotation.z,
        scaleX = 2,
        scaleY = 2,
        scaleZ = 2
      }
    }
  })
end
