VALID_TOKENS    = {
  ["Skull"]       = true,
  ["Cultist"]     = true,
  ["Tablet"]      = true,
  ["Elder Thing"] = true,
  ["Blood"]       = true
}

require("playercards/CardsThatSealTokens")

local ChaosBagApi = require("chaosbag/ChaosBagApi")

function onLoad2()
  self.addContextMenuItem("Seal From Play", triggerXMLTokenLabelCreation)
end

function triggerXMLTokenLabelCreation(playerColor)
  ChaosBagApi.removeTokenFromPlay("seal", VALID_TOKENS, nil, nil, nil, self.getGUID(), playerColor)
end

function sealTokenWrapper(params)
  sealToken(params.tokenName, params.playerColor)
end
