-- this example data is used for Zoop-created cards (e.g. NoV)
local FRONT_ANGLE = Vector(180, 0, 0)
local BACK_ANGLE  = Vector(180, 0, 90)

function onLoad()
  updateAltPreview()
end

function onRotate(_, flip)
  updateAltPreview(flip >= 90 and flip <= 270)
end

function onDrop()
  updateAltPreview()
end

function updateAltPreview(useBack)
  if useBack == nil then
    useBack = self.is_face_down
  end

  self.alt_view_angle = useBack and BACK_ANGLE or FRONT_ANGLE
end
