-- this example data is used for the Masked Hunter (NotZ - Midnight Masks, Agenda 1b)
local FRONT_ANGLE = Vector(180, 0, 270)
local BACK_ANGLE  = Vector(180, 0, 180)

function onLoad()
  updateAltPreview()
end

function onRotate(_, flip)
  updateAltPreview(flip >= 90 and flip <= 270)
end

function onDrop()
  updateAltPreview()
end

function updateAltPreview(useBack)
  if useBack == nil then
    useBack = self.is_face_down
  end

  self.alt_view_angle = useBack and BACK_ANGLE or FRONT_ANGLE
end
