do
  local HelperLib     = {}

  local DeckLib       = require("util/DeckLib")
  local MythosAreaApi = require("mythos/MythosAreaApi")
  local PlayAreaApi   = require("playarea/PlayAreaApi")
  local PlayermatApi  = require("playermat/PlayermatApi")
  local SearchLib     = require("util/SearchLib")
  local TableLib      = require("util/TableLib")

  local OFFSET_X      = 2
  local OFFSET_Z      = 2
  local MINI_OFFSET   = {
    Vector(OFFSET_X, 0, OFFSET_Z),
    Vector(-OFFSET_X, 0, OFFSET_Z),
    Vector(-OFFSET_X, 0, -OFFSET_Z),
    Vector(OFFSET_X, 0, -OFFSET_Z),
  }

  -- Checks if a card has clues on it
  ---@param card tts__Object Card to check for clues
  ---@return boolean hasClues True if card has clues on it
  function HelperLib.cardHasClues(card)
    return #SearchLib.onObject(card, "isClue") > 0
  end

  function HelperLib.getMetadata(objectOrNotes)
    if objectOrNotes == nil then return {} end
    local rawNotes
    if type(objectOrNotes) == "string" then
      rawNotes = objectOrNotes
    elseif type(objectOrNotes) == "table" then
      rawNotes = objectOrNotes["GMNotes"] or objectOrNotes["gm_notes"]
    else
      rawNotes = objectOrNotes.getGMNotes()
    end
    return JSON.decode(rawNotes) or {}
  end

  -- Simple method to check if the given point is in a specified area
  ---@param point tts__Vector Point to check, only x and z values are relevant
  ---@param bounds table Defined area to see if the point is within
  function HelperLib.isInArea(point, bounds)
    return (point.x > bounds.minX
      and point.x < bounds.maxX
      and point.z > bounds.minZ
      and point.z < bounds.maxZ)
  end

  ---@param container tts__Object Container to check
  ---@param guid string GUID to search for
  ---@return boolean: Whether there is an object with this GUID in the container
  function HelperLib.checkContainerForGuid(container, guid)
    if container ~= nil and container.getData().ContainedObjects then
      for _, info in ipairs(container.getObjects()) do
        if info.guid == guid then
          return true
        end
      end
    end
    return false
  end

  function HelperLib.moveInvestigatorMinis(grid, name)
    local shouldMove = {}
    for _, matColor in ipairs(PlayermatApi.getUsedMatColors()) do
      local miniId = PlayermatApi.getActiveInvestigatorData(matColor).miniId
      shouldMove[miniId] = true
    end

    local movedMiniCount = 0
    local basePos        = PlayAreaApi.gridToWorld(grid)
    for _, minicard in ipairs(getObjectsWithTag("MiniCard")) do
      local md = JSON.decode(minicard.getGMNotes())
      if md and md.id and shouldMove[md.id] then
        movedMiniCount = movedMiniCount + 1
        minicard.setPosition(basePos + MINI_OFFSET[movedMiniCount])
        shouldMove[md.id] = nil
      end
    end

    if movedMiniCount > 0 and name then
      printToAll(string.format("Moved %d mini cards to %s.", movedMiniCount, name))
    end
  end

  function HelperLib.spawnMythosDeckOrCard(objects, name, shuffle)
    if #objects == 0 then return end

    local position
    local rotation = MythosAreaApi.getRotation()
    if name == "Act Deck" then
      position = MythosAreaApi.getActPosition()
      rotation = rotation - Vector(0, 90, 0)
    elseif name == "Agenda Deck" then
      position = MythosAreaApi.getAgendaPosition()
      rotation = rotation - Vector(0, 90, 0)
    elseif name == "Encounter Deck" then
      position = MythosAreaApi.getEncounterDeckPosition()
      rotation = rotation + Vector(0, 0, 180)
    else
      printToAll("Unhandled name for 'spawnMythosDeckOrCard()'!")
      return
    end

    if shuffle then
      TableLib.shuffle(objects)
    elseif name == "Act Deck" or name == "Agenda Deck" then
      table.sort(objects, function(a, b) return a.Description > b.Description end)
    end

    if #objects == 1 then
      return DeckLib.spawnCard(objects[1], position, rotation)
    else
      local deckdata = DeckLib.generateDeckData(objects, position, rotation)
      deckdata.Nickname = name
      if name == "Encounter Deck" then
        deckdata.HideWhenFaceDown = true
      end
      return spawnObjectData({ data = deckdata })
    end
  end

  return HelperLib
end
