local readOnly

function updateSave()
  self.script_state = JSON.encode({ readOnly = readOnly })
end

function onLoad(savedData)
  if savedData and savedData ~= "" then
    local loadedData = JSON.decode(savedData)
    readOnly = loadedData.readOnly
  end

  if readOnly == nil then
    readOnly = true
  end

  self.max_typed_number = 0
end

function setReadOnly(newState)
  readOnly = newState
  updateSave()
end

-- only allow cards to enter, split decks and reject other objects
function tryObjectEnter(object)
  if readOnly then return end
  if object.getName() == lastRejectedName then return end

  if object.type == "Deck" then
    object.shuffle()
    local pos = self.getPosition()
    for i = 1, #object.getObjects() do
      local card = object.takeObject({ position = pos + Vector(0, 0.1 * i, 0), smooth = false })
      self.putObject(card)
    end
    return false
  elseif object.type ~= "Card" then
    lastRejectedName = object.getName()
    Wait.time(function() lastRejectedName = nil end, 1)
    return false
  end

  return true
end
